model_name_or_path: SpectraSuite/spectra2-2b-base
model_revision: main
use_flash_attn: true
tokenizer_name: SpectraSuite/spectra2-2b-base
use_slow_tokenizer: false
dataset_mixer:
    allenai/tulu-3-sft-mixture: 1.0
preprocessing_num_workers: 128
per_device_train_batch_size: 4 # note, this is set up for 8 GPUs
gradient_accumulation_steps: 2 # effective batch size = 4 BS x 2 GradAccum x 4GPUs= 32
learning_rate: 1.0e-5
max_seq_length: 2048
lr_scheduler_type: linear
warmup_ratio: 0.03
weight_decay: 0.0
num_train_epochs: 1
checkpointing_steps: 500
# max_train_steps: 10000
output_dir: /home/mila/a/ayush.kaushal/scratch/pshishodia/open-instruct/spectra_2_2b/
with_tracking: true
report_to:
  - wandb
logging_steps: 1
dataset_mix_dir: /home/mila/a/ayush.kaushal/scratch/pshishodia/open-instruct/output/float_lm_1b
trust_remote_code: true
push_to_hub: false
try_launch_beaker_eval_jobs: false
wandb_project_name: spectra_2_2b_sft